### ISSUE TITLE
How can i use this library in native java android application? not kotlin, i am not able to call this method from java

### ISSUE THREAD

**Issue by arunrajgm** [SuddenH4X/awesome-app-rating#14]

**Comment by SuddenH4X** [comment]
Hi @arunrajgm,

you can easily use this library from java code. For example:
```java
 @Override
 protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.activity_main);

     new AppRating.Builder(this)
             .setMinimumLaunchTimes(5)
             .setMinimumDays(7)
             .setMinimumLaunchTimesToShowAgain(5)
             .setMinimumDaysToShowAgain(10)
             .setRatingThreshold(RatingThreshold.FOUR)
             .showIfMeetsConditions();
 }
```

**Comment by arunrajgm** [comment]
Works fine, thanks for your help, if possible please update the readme for java call too.
Same time if I launch the app five times in a single-day pop up will open or not?
I closed and reopened lot of time but popup not opened, one time app getting crashed too, I hope its exactly 5th time but not sure.

**Comment by SuddenH4X** [comment]
It depends on your configuration. If you set `setMinimumLaunchTimes(5)` and also `setMinimumDays(0)`, the dialog will show up after five launches even in a single day. I would recommend you to look into the readme for more information and also for the default values.
