### ISSUE TITLE
Google in app review not working using via java code

### ISSUE THREAD

**Issue by arunrajgm** [SuddenH4X/awesome-app-rating#20]
Hey, I upgrade the library version as 
`    implementation 'com.suddenh4x.ratingdialog:awesome-app-rating:2.2.0' `

I am using this library in an android java project, the previous version works fine, but I am trying to use in google in-app review, but it does nothing, I tried most of the possibilities, below is one of the possibility. I am executing this code in AppCompatActivity class.

`new AppRating.Builder(this)
                .setDebug(true).useGoogleInAppReview().showNow();`

I am testing the code on Samsung m30, Android 10.

Waiting for the reply, Thanks in advance

**Comment by SuddenH4X** [comment]
Hi @arunrajgm,

testing the in-app review isn't as easy as it should be. I've also experienced some issues with testing the Google In-App Review API. Follow the tips on stackoverflow and test it again:

> -  Use only one account in the device
> -  Ensure that account has installed the app (appears in the app & games > Library section in Play Store)
> -  The account is a GMAIL one, not a GSuit
> -  You can review with the account if you go to the app play listing page.
> -  The account has not reviewed
> -  If you intend to use the Internal Test Track ensure the account has joined the test track.
> -  When switching between different accounts and testing things out, sometimes might be helpful to "Clear Data" from the Play Store app.
> -  Try all the above with different account

Source: https://stackoverflow.com/a/63950373

You can also use [Internal App Sharing](https://play.google.com/apps/publish/internalappsharing) to skip the quota verification (see https://developer.android.com/guide/playcore/in-app-review/test).

**Comment by SuddenH4X** [comment]
You can also add a listener with `.setGoogleInAppReviewCompleteListener(googleInAppReviewCompleteListener: (Boolean) -> Unit)`. If it's getting invoked with `true` the request itself should have finished correctly.

There is an open issue in the issuetracker of google. If it's still not working you could look into it: https://issuetracker.google.com/issues/167352813

**Comment by arunrajgm** [comment]
@SuddenH4X Really thanks for your reply, I understood the problem.  Just from my point of view, it won't work all the time(only some time if the conditions are met), its better to leave as it is without in-app-review, once we get a 100% result from google, we can use this option.
