### ISSUE TITLE
Google In App review dialog never show.

### ISSUE THREAD

**Issue by samir-shaikh28** [SuddenH4X/awesome-app-rating#22]
Hey, I've been trying to use Google In app review feature from awesome-app-rating but everytime I'm getting Toast "Google In-App review completed success: true" and dialog never shown. my app is already published on play store. I've tried in multiple OS across multiple device.

**Comment by SuddenH4X** [comment]
Hi @samir-shaikh28,

I've just added this to the readme:

Testing the Google in-app review isn't as easy as it should be. There is an open issue in the issuetracker of Google: https://issuetracker.google.com/issues/167352813

Follow these tips on stackoverflow to maximize your chance of testing it successfully:

```
- Use only one account in the device
- Ensure that account has installed the app (appears in the app & games > Library section in Play Store)
- The account is a GMAIL one, not a GSuit
- You can review with the account if you go to the app play listing page.
- The account has not reviewed
- If you intend to use the Internal Test Track ensure the account has joined the test track.
- When switching between different accounts and testing things out, sometimes might be helpful to "Clear Data" from the Play Store app.
- Try all the above with different account

Source: https://stackoverflow.com/a/63950373
```

You should consider to wait with implementing it and use the normal rating dialog instead until Google has fixed the issue(s).

**Comment by itsniaz** [comment]
@samir-shaikh28 
I initially face the same issue building a signed APK and run it on the device. It should show up.

**Comment by SuddenH4X** [comment]
I will close this issue because I didn't see any issues with the Google in-app review since 2021. And I've also just removed the in-app review warning from the readme (see #77).
