### ISSUE TITLE
Google InAppRatingDialog with LibraryDialog 

### ISSUE THREAD

**Issue by jansvanda** [SuddenH4X/awesome-app-rating#32]
Hello, I like your lib, as it makes my life much easier.
I thought it would be so cool, if you could combine the original Library Dialog with the Google Inapp review dialog,
something like:
.combineOriginalandGoogleDialog
The Process would be almost same as the Library Dialog, but when the user selects the Stars or chooses "yes, i want to rate", it would open the Google Dialog to rate. 

This would enhance the user experience, as it firstly asks you if you even want to rate. 
.
Thank you for stating your point of view.

jan

**Comment by SuddenH4X** [comment]
Hi @jansvanda,

Initially, I also thought about that. But as mentioned in https://github.com/SuddenH4X/awesome-app-rating/pull/28 it isn't allowed to do that.

**Comment by jansvanda** [comment]
Okay hm
 I find it too much unexpected when suddenly a dialog appears. Could lead to missclicks etc
I use an dialog combined with inappreview and it is really good. 

Btw before this new rating api, you could have created dialogs before opening the view with the rating section? (Gplay app overview)
Now you can't? Ehm

**Comment by SuddenH4X** [comment]
I'm not sure if I understand your problem. Of course you can just create the rating dialog and show it whenever you want. This behaviour didn't change.

**Comment by Monabr** [comment]
Maybe you understood it wrong? It said "no questions", but it didn't said "no dialogs before in-app review" so i can simply show dialog with "rate our app" and only then show in-app review

**Comment by SuddenH4X** [comment]
Hi @Monabr,

if you show a dialog with the text "rate our app" and two options (rate / cancel) I think Google will interprete this as question equally. Also there is another issue with that approach: Google decides if the in-app review will be shown or not. So there would be users that click on the "rate" button and don't see the dialog and that would be confusing.

**Comment by Monabr** [comment]
@SuddenH4X,

Are you sure about this? Judging by what I read in the documentation, there are several conditions for showing - there was no assessment before, the person has a google play and he is logged in, that's it. In addition to all this, the manager of this window seems to have a method by which you can check in advance whether it is possible to display a dialog, this is again from my memory.

**Comment by SuddenH4X** [comment]
As you can see in [this issue](https://issuetracker.google.com/issues/167352813) the in app review isn't as reliable as it should be. And in the [official documentation](https://developer.android.com/guide/playcore/in-app-review#quotas) you can read the following: 

> You should not have a call-to-action option (such as a button) to trigger the API, as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user.

The method that you are mentioning returns a boolean which indicates if the flow was started correctly, but not if the in-app review can be displayed or was displayed to the user. You can also get that response by using the method `.setGoogleInAppReviewCompleteListener(googleInAppReviewCompleteListener: (Boolean) -> Unit)` of this library. But I don't think that this method could be helpful in this specific case, even if it would be allowed.
