### ISSUE TITLE
Duplicate dialogs.

### ISSUE THREAD

**Issue by Monabr** [SuddenH4X/awesome-app-rating#33]
The problem is if we rotate the screen - dialog will appear one more time upon the old one.

**Comment by SuddenH4X** [comment]
Hi @Monabr,

thanks for opening the issue. I couldn't reproduce the duplicate dialogs. Are you using the latest library version? Do you show it from fragment or activity? And can you please share me your rating dialog building code?

**Comment by Monabr** [comment]
I am show it from activity. The problem is that this works from onCreate, and your dialog doesn't make any checks after .showIfMeetsConditions(), so it will be show one more time if i didn't click, for example, "later".

**Comment by Monabr** [comment]
for now i am using this code to fix this behavior 
`if (supportFragmentManager.findFragmentByTag(AppRating::class.java.simpleName) == null)`

**Comment by SuddenH4X** [comment]
Thanks again for opening this issue. I've fixed it within #40.
