### ISSUE TITLE
Cancelable

### ISSUE THREAD

**Issue by Monabr** [SuddenH4X/awesome-app-rating#34]
I think setCancelable is missing some logic. In my opinions it should works (or have logic) like button "later"

**Comment by SuddenH4X** [comment]
Hi @Monabr,

I think you're right! I will look into that and probably release an update next week. Thanks!

**Comment by Monabr** [comment]
Thank you! I will look forward to it!

**Comment by SuddenH4X** [comment]
I fixed it on branch `fix_cancelable_34` if you want to check it out. I'm planning to release a new version with this and other fixes/updates next week.
