### ISSUE TITLE
Customize labels and text

### ISSUE THREAD

**Issue by daimonkor** [SuddenH4X/awesome-app-rating#35]
Hello. Please add additional functions to customize button labels and titles with help simple string. I have different localization  API (libgdx). I found only function with resourses ids and there is the problem. Thanks for help.

**Comment by SuddenH4X** [comment]
Hi @daimonkor,

using String ressources instead of Strings is the way to go in Android. I wouldn't recommend using another localization method. Are you sure that libgdx isn't supporting this?
