### ISSUE TITLE
Failed to send email when targeting Android 11

### ISSUE THREAD

**Issue by ay1man4** [SuddenH4X/awesome-app-rating#36]
Hello,

Thank you for your awesome library!

I found that sending email feedback always fail due to Android 11 restriction illustrated in below link:

[Package visibility in Android 11](https://developer.android.com/about/versions/11/privacy/package-visibility)

To resolve this issue, we have to add query to mainfaist file like this:

```  
<queries>
        <!-- Sending Emails   -->
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data android:scheme="mailto" />
        </intent>
</queries>
```

Thank you

**Comment by SuddenH4X** [comment]
Hi @ay1man4,

thank you for opening this issue. I will fix it with the next release which is planned for the end of this week 🙂
