### ISSUE TITLE
Add discreet rate option

### ISSUE THREAD

**Issue by rosenpin** [SuddenH4X/awesome-app-rating#42]
Instead of showing a dialog that blocks user interactions with the app, I think in some cases it would be a lot better to show a Snackbar instead.

It could look like
``` kotlin
        AppRating.Builder(activity)
            .discreet()
            .setMinimumLaunchTimes(5)
            .setMinimumDays(2)
            .setMinimumLaunchTimesToShowAgain(8)
            .setMinimumDaysToShowAgain(4)
            .showIfMeetsConditions()
````

In which case, instead of showing a dialog with starts and everything, it will only show a snackbar with a short message and a "rate now" button

This will also allow compliance with Google's in app rate library, which requires that you don't ask the user how much they would like to rate the app before showing the rate dialog ([source](https://developer.android.com/guide/playcore/in-app-review#when-to-request))

This will let us show the user the rate request more often, as it's less intrusive  
And I believe users will get less pissed off about a dialog blocking their app when they want to use it

**Comment by SuddenH4X** [comment]
Hi @rosenpin,

in the [official documentation](https://developer.android.com/guide/playcore/in-app-review#quotas) you can read the following: 

> You should not have a call-to-action option (such as a button) to trigger the API, as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user.

So the method wouldn't be compliant with the Google guidelines. Of course the snackbar could be used to redirect the user directly to the Play Store but I think a redirect would be annoying too. Additionally this feature (Snackbar + redirect) could be easily implemented without using a library.

**Comment by rosenpin** [comment]
Got you

This can be closed
