### ISSUE TITLE
Can we change rating overview title after creating the dialog?

### ISSUE THREAD

**Issue by VinodRanganath** [SuddenH4X/awesome-app-rating#52]
We have a requirement wherein we need to insert the user's name in the review overview's title, like so "Hey <username>, how was your experience with this app?". Considering the text comes from the string resource during compilation time, is it possible to change it after creating the dialog with the create() method?

**Comment by SuddenH4X** [comment]
Hi @VinodRanganath, thanks for opening this issue. This is something I forgot to think about. Sadly it isn't possible at the moment but I will add this feature with the next release.

**Comment by VinodRanganath** [comment]
@SuddenH4X Thank you
