### ISSUE TITLE
Only available on jcenter repository which is deprecated

### ISSUE THREAD

**Issue by inidamleader** [SuddenH4X/awesome-app-rating#55]

**Comment by SuddenH4X** [comment]
Hi @inidamleader, I'm aware of this issue and will migrate to Maven Central in the next 3-4 weeks.

**Comment by inidamleader** [comment]
You may be should to mention on README, that this lib rely on jcenter(), because at my first integration I didn’t figure out why gradle fails to include this lib. Thank you, this is a beautiful lib.

**Comment by SuddenH4X** [comment]
Thanks for the compliment! I'm currently releasing the library to Maven Central and hope to finish the migration in the next few days. And with the new release I will extend the readme to avoid any confusion 😉

**Comment by shivamsoods** [comment]
Hey
Just found your awesome library, hoping that you would soon switch to Maven Central. Waiting for this so that I can finally update my app on the playstore.

**Comment by SuddenH4X** [comment]
It was a lot more work than expected but I finally got it uploaded to Maven Central. Just use the version 2.4.0 of the library 😉

**Comment by shivamsoods** [comment]
Wow that is great!
Looking forward to integrate it in my application. Thanks a lot
