### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by inidamleader** [SuddenH4X/awesome-app-rating#61]
On my crash analytics I get this crash report:
Fatal Exception: java.lang.IllegalStateException Can not perform this action after onSaveInstanceState

androidx.fragment.app.FragmentManager.checkStateLoss (FragmentManager.java:1844)
androidx.fragment.app.DialogFragment.show (DialogFragment.java:260)
com.suddenh4x.ratingdialog.AppRating$Builder.showNow (AppRating.java:309)
com.suddenh4x.ratingdialog.AppRating$Builder.showIfMeetsConditions (AppRating.java:328)
com.inidamleader.ovtracker.reviewer.AppRatingReviewer.launchReviewFlow (AppRatingReviewer.java:63)
com.inidamleader.ovtracker.reviewer.ReviewerImpl.launchReviewFlowIfPossible (ReviewerImpl.java:40)
com.inidamleader.ovtracker.activity.MainActivity$onCreate$initReviewers$1.invokeSuspend (MainActivity.java:209)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
kotlinx.coroutines.DispatchedTaskKt.resume (DispatchedTaskKt.java:227)
kotlinx.coroutines.DispatchedTaskKt.dispatch (DispatchedTaskKt.java:166)
kotlinx.coroutines.CancellableContinuationImpl.dispatchResume (CancellableContinuationImpl.java:362)
kotlinx.coroutines.CancellableContinuationImpl.resumeImpl (CancellableContinuationImpl.java:396)
kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default (CancellableContinuationImpl.java:388)
kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched (CancellableContinuationImpl.java:484)
kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run (HandlerContext.java:19)

**Comment by SuddenH4X** [comment]
Hi @inidamleader, can you share some more information regarding this issue? How and when do you call the library?

**Comment by inidamleader** [comment]
Sorry that was a bug caused by showing a FragmentDialog that is caused by my own code:
https://medium.com/degoo/demystifying-androids-fragmenttransaction-and-solving-can-not-perform-this-action-after-3d45004aa22f
