### ISSUE TITLE
Unable to find the AppRating class 

### ISSUE THREAD

**Issue by RachidLeLaborantin** [SuddenH4X/awesome-app-rating#65]
I use Android Studio and Java, I want to use your library but I can't find the AppRating class. I've successfully implemented the git repository
Is because the library is in kotlin? It don't work with java projects?

**Comment by SuddenH4X** [comment]
Hi @RachidLeLaborantin,

Of course the library is also working with java projects. Can you share a little bit more details of your integration? How and where did you add the dependency?
