### ISSUE TITLE
Use Google in-app review if conditions are met

### ISSUE THREAD

**Issue by soenkegissel** [SuddenH4X/awesome-app-rating#69]
If I use .useGoogleInAppReview() the Google in-app review is shown straight away. 
I like to show dialog with star rating upfront, if threshold is met show "we like to get 5 stars from you" and on rate button click not open the Google Play Store listing but open the Google in-app review.

A flow like this:
![image](https://user-images.githubusercontent.com/13346316/176039646-906f66bd-fe56-49e5-a723-198bd267f46f.png)

**Comment by SuddenH4X** [comment]
Hi @soenkegissel, this is a duplicate of #28 and #32 so I will close this now. If you have another issue feel free to open one 😉
