### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by jawegielewski** [SuddenH4X/awesome-app-rating#73]
Hello 

I have two issues. 

1) When I open "Give feedback" dialog and then submit - nothing happens.

2) Height of those dialogs are much to long I mean button are located properly but bottom of dialogs is long below those buttons.

Please give me a solución because I like this project :)

Regards
Jakub

**Comment by SuddenH4X** [comment]
Hi @jawegielewski,

1. Did you read the readme, especially the [mail feedback part](https://github.com/SuddenH4X/awesome-app-rating#mail-feedback)? If yes, which library logs do you see in Logcat?
2. This shouldn't be the case and I can't reproduce it myself. Can you share your device, android version and a screenshot of the bug?

Best regards,
SuddenH4X
