### ISSUE TITLE
How to chand Rating Dialog Background and Button Color Manually??

### ISSUE THREAD

**Issue by imomis77** [SuddenH4X/awesome-app-rating#8]
i want to change the dialog background color and button color manually.

How it's possible??

**Comment by SuddenH4X** [comment]
Hi @imomis77,

you have to change the colors directly in your app's theme. The buttons use the accent color of your theme in `styles.xml`:
```kotlin
<item name="colorAccent">@color/yourColor</item>
```
And the background color uses the app wide one of your theme in `styles.xml`:
```kotlin
<item name="android:background">@color/yourColor</item>
```

You could also create the dialog with the `create()` method and then set a custom style with `setStyle(int style, int theme)`. So you could change the background color for the rating dialog only.

**Comment by imomis77** [comment]
Thanks for responding.

**Comment by VittoriDavide** [comment]
@SuddenH4X is there any way to create to change the style and after that call showIdMeetConditions()
