### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by dvaoru** [SuddenH4X/awesome-app-rating#82]
After I start using this library in my app, I'm getting this exception in Firebase crash reports:  
**Fatal Exception: java.lang.RuntimeException
Parcelable encountered IOException writing serializable object (name = com.suddenh4x.ratingdialog.dialog.DialogOptions)**

But I don't know how it affects on user experience.

**Comment by SuddenH4X** [comment]
I can't reproduce this issue. Do you have a full stacktrace and more information for me? (like how often this crash occurs, which devices, ...)

**Comment by dvaoru** [comment]
Hello.

Thank you for your attention.
I have solved this issue for myself, by making
*com.suddenh4x.ratingdialog.dialog.DialogOptions*
class not Serializable but Parcelable.
I did not reproduce the issue too, but I got a lot of this on Crashlytics.
After I make *DialogOptions* Parcelable and update my app, I don't have any
troubles.

Thank you for your project, it is really helpful!

Best regards
Dvaoru.

сб, 21 янв. 2023 г. в 18:50, SuddenH4X ***@***.***>:

**Comment by SuddenH4X** [comment]
Alright, thanks for sharing your solution!
