### ISSUE TITLE
Not clear about Jetpack Compose 

### ISSUE THREAD

**Issue by arijit4** [SuddenH4X/awesome-app-rating#86]
No documentation in the `ReadMe` file to implement this awesome library in Jetpack Compose.

**Comment by SuddenH4X** [comment]
Hi @arijit4, there is a part in the readme regarding Jetpack Compose 😉 

https://github.com/SuddenH4X/awesome-app-rating#jetpack-compose

**Comment by arijit4** [comment]
Oh, sorry, I missed that. But can I use this library withou migrating to `FragmentActivity` from `ComponentActivity`?

**Comment by SuddenH4X** [comment]
As descriped in the readme you have to switch to `AppCompatActivity` or `FragmentActivity` to use the library dialog. Or you can use the official Google in-app review (also with this library) by calling `.useGoogleInAppReview()`.
